"""
Requirement Refinement Models

Data models for LLM-driven requirement refinement and clarification.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class RefineQuestion(BaseModel):
    """A single refinement question generated by LLM."""
    
    id: str = Field(..., description="Question ID (e.g., Q1, Q2)")
    question: str = Field(..., description="The question text")
    why_asking: str = Field(..., description="Explanation of why this information is needed")
    suggestions: List[str] = Field(default_factory=list, description="Possible answer suggestions")


class RefineResult(BaseModel):
    """Result of requirement refinement analysis."""
    
    # Current conversation round
    round: int = Field(..., description="Current refinement round number")
    
    # LLM's understanding summary (Markdown format)
    understanding_summary: str = Field(..., description="LLM's understanding of the requirement in 2-3 sentences")
    
    # Inferred assumptions by LLM
    inferred_assumptions: List[str] = Field(default_factory=list, description="Assumptions inferred by LLM")
    
    # Key clarification questions (1-2 questions)
    questions: List[RefineQuestion] = Field(default_factory=list, description="Key questions to ask user")
    
    # Whether requirement is clear enough to compile
    ready_to_compile: bool = Field(False, description="Whether requirement is clear enough to proceed to compilation")
    
    # Draft spec if ready (optional)
    draft_spec: Optional[Dict[str, Any]] = Field(None, description="Draft spec structure if ready_to_compile is True")


class RefineContext(BaseModel):
    """Context for requirement refinement conversation."""
    
    # Conversation history
    conversation_history: List[Dict[str, str]] = Field(default_factory=list, description="List of {role: user/assistant, content: ...}")
    
    # Current round
    round: int = Field(0, description="Current refinement round")
    
    # Feature ID if already created
    feature_id: Optional[str] = Field(None, description="Feature ID if spec has been created")
    
    # Any additional context
    additional_context: Dict[str, Any] = Field(default_factory=dict, description="Additional context for refinement")
